name: Update Language Statistics

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: StefVuck/Github-Language-Stats@v1.2.0
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: 'leaderboard bar pie donut'
          output_path: 'stats'
          exclude_languages: 'HTML,CSS'
          dark_mode: "true"
