name: Update Language Statistics

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'stats/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure Git, remove the directory, and commit the deletion to keep the index clean.
      - name: Clean stats directory
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git rm -rf stats || true
          git commit -m "Clean old stats directory" || true

      - name: Generate statistics
        uses: StefVuck/Github-Language-Stats@v1.2.0
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: 'leaderboard bar pie donut'
          output_path: 'stats'
          exclude_languages: 'HTML,CSS'
          dark_mode: 'true'
